<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="49515" started-at="2018-06-10T04:48:22Z" finished-at="2018-06-10T04:49:12Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="49515" started-at="2018-06-10T04:48:22Z" finished-at="2018-06-10T04:49:12Z">
      <class name="com.facebook.TestCases.LoginTest">
        <test-method status="PASS" signature="LoginTestCase(java.lang.String, java.lang.String)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4]" name="LoginTestCase" duration-ms="10131" started-at="2018-06-10T10:18:23Z" data-provider="sendData" finished-at="2018-06-10T10:18:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumforsure@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password_123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestCase -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4]" name="tearDown" is-config="true" duration-ms="6" started-at="2018-06-10T10:18:33Z" finished-at="2018-06-10T10:18:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginTestCase status=SUCCESS method=LoginTest.LoginTestCase(java.lang.String, java.lang.String)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LoginTestCase(java.lang.String, java.lang.String)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4]" name="LoginTestCase" duration-ms="19728" started-at="2018-06-10T10:18:33Z" data-provider="sendData" finished-at="2018-06-10T10:18:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumforsure2@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password_1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.facebook.TestCases.LoginTest.LoginTestCase(LoginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestCase -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4]" name="tearDown" is-config="true" duration-ms="386" started-at="2018-06-10T10:18:53Z" finished-at="2018-06-10T10:18:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginTestCase status=FAILURE method=LoginTest.LoginTestCase(java.lang.String, java.lang.String)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="FAIL" signature="LoginTestCase(java.lang.String, java.lang.String)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4]" name="LoginTestCase" duration-ms="18647" started-at="2018-06-10T10:18:53Z" data-provider="sendData" finished-at="2018-06-10T10:19:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumforsure1@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password_123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login failed expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.facebook.TestCases.LoginTest.LoginTestCase(LoginTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginTestCase -->
        <test-method status="PASS" signature="tearDown(org.testng.ITestResult)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4]" name="tearDown" is-config="true" duration-ms="272" started-at="2018-06-10T10:19:12Z" finished-at="2018-06-10T10:19:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=LoginTestCase status=FAILURE method=LoginTest.LoginTestCase(java.lang.String, java.lang.String)[pri:0, instance:com.facebook.TestCases.LoginTest@18be83e4] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.facebook.TestCases.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
